### ISSUE TITLE
python 3 + Big Sur + libgfortran.4.dylib

### ISSUE THREAD

**Issue by carolinestraatman** [JohannesBuchner/PyMultiNest#187]
I recently upgraded to Big Sur and python 3 at the same time. Since then, I cannot import the PyMultiNest package. I get the following error:

```
In [1]: import pymultinest
problem: dlopen(/usr/local/lib/libmultinest.dylib, 6): Library not loaded: /opt/local/lib/libgcc/libgfortran.4.dylib
  Referenced from: /usr/local/lib/libmultinest.3.10.dylib
  Reason: image not found
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/caro/software/PyMultiNest/pymultinest/run.py", line 16, in _load_library
    return cdll.LoadLibrary(libname)
  File "/Users/caro/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/Users/caro/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libmultinest.dylib, 6): Library not loaded: /opt/local/lib/libgcc/libgfortran.4.dylib
  Referenced from: /usr/local/lib/libmultinest.3.10.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caro/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-258cb5fc2840>", line 1, in <module>
    import pymultinest
  File "/Users/caro/software/PyMultiNest/pymultinest/__init__.py", line 19, in <module>
    from .run import run
  File "/Users/caro/software/PyMultiNest/pymultinest/run.py", line 52, in <module>
    lib = _load_library('libmultinest')
  File "/Users/caro/software/PyMultiNest/pymultinest/run.py", line 50, in _load_library
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caro/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/caro/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/Users/caro/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/caro/opt/anaconda3/lib/python3.8/inspect.py", line 1515, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/software/PyMultiNest/pymultinest/run.py in _load_library(libname)
     15                         libname = find_library(libname)
---> 16                 return cdll.LoadLibrary(libname)
     17         except OSError as e:

~/opt/anaconda3/lib/python3.8/ctypes/__init__.py in LoadLibrary(self, name)
    458     def LoadLibrary(self, name):
--> 459         return self._dlltype(name)
    460 

~/opt/anaconda3/lib/python3.8/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    380         if handle is None:
--> 381             self._handle = _dlopen(self._name, mode)
    382         else:

OSError: dlopen(/usr/local/lib/libmultinest.dylib, 6): Library not loaded: /opt/local/lib/libgcc/libgfortran.4.dylib
  Referenced from: /usr/local/lib/libmultinest.3.10.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-1-258cb5fc2840> in <module>
----> 1 import pymultinest

~/software/PyMultiNest/pymultinest/__init__.py in <module>
     18 try:
---> 19         from .run import run
     20         from .solve import solve, Solver

~/software/PyMultiNest/pymultinest/run.py in <module>
     51 
---> 52 lib = _load_library('libmultinest')
     53 

~/software/PyMultiNest/pymultinest/run.py in _load_library(libname)
     49                 print('problem:', e)
---> 50                 sys.exit(1)
     51 

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2052                     stb = ['An exception has occurred, use %tb to see '
   2053                            'the full traceback.\n']
-> 2054                     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2055                                                                      value))
   2056                 else:

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    752         value : exception value
    753         """
--> 754         return ListTB.structured_traceback(self, etype, value)
    755 
    756     def show_exception_only(self, etype, evalue):

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    627             chained_exceptions_tb_offset = 0
    628             out_list = (
--> 629                 self.structured_traceback(
    630                     etype, evalue, (etb, chained_exc_ids),
    631                     chained_exceptions_tb_offset, context)

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1365         else:
   1366             self.tb = tb
-> 1367         return FormattedTB.structured_traceback(
   1368             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1369 

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1265         if mode in self.verbose_modes:
   1266             # Verbose modes need a full traceback
-> 1267             return VerboseTB.structured_traceback(
   1268                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1269             )

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1122         """Return a nice text document describing the traceback."""
   1123 
-> 1124         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1125                                                                tb_offset)
   1126 

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1080 
   1081 
-> 1082         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1083 
   1084         frames = self.format_records(records, last_unique, recursion_repeat)

~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
------------------------------------------

Presumably it will be necessary to upgrade/downgrade something. What would you advise?

This is what I have installed:
>> ls /opt/local/lib/libgcc/
libasan.5.dylib       libgcc_ext.10.5.dylib libgomp.1.dylib       libquadmath.0.dylib   libubsan.1.dylib
libatomic.1.dylib     libgcc_s.1.dylib      libitm.1.dylib        libssp.0.dylib
libgcc_ext.10.4.dylib libgfortran.5.dylib   libobjc-gnu.4.dylib   libstdc++.6.dylib
```

**Comment by JohannesBuchner** [comment]
Did you rerun cmake for MultiNest, with a clean build directory?

**Comment by carolinestraatman** [comment]
yes, I did that first

**Comment by JohannesBuchner** [comment]
This may be the key line:

`OSError: dlopen(/usr/local/lib/libmultinest.dylib, 6): Library not loaded: /opt/local/lib/libgcc/libgfortran.4.dylib`

Perhaps your cmake picked the wrong compiler?

**Comment by carolinestraatman** [comment]
That’s probably true, but how do you fix that?

**Comment by JohannesBuchner** [comment]
Have you tried the solutions that come up when googling the error message? 

https://stackoverflow.com/questions/57207357/dyld-library-not-loaded-usr-local-gfortran-lib-libgfortran-3-dylib-reason-im

**Comment by carolinestraatman** [comment]
Thanks for the suggestion. I do not have libgfortran.4.dylib (can’t be located). I was reluctant to install other versions of gcc, because I’m not an expert and I don’t want to mess up other dependencies. That being said, I’ve now tried installing many versions of gcc, but no matter how I try or google for it separately, I cannot get my hands on this specific file.

gcc4 seems to be getting outdated, e.g., I get an error from MacPorts because it’s no longer supported.

Is there no way cmake can “grab” a more recent version of gcc? Should I wait for updates on pymultinest/multinest?

**Comment by carolinestraatman** [comment]
the problem has been solved in a different way:

another option is to use Anaconda/Miniconda, and create a new environment and then install MultiNest from conda-forge, e.g., conda install -c conda-forge multinest (or just install PyMultiNest through conda, conda install -c conda-forge pymultinest, and it will install multinest too)
(https://github.com/JohannesBuchner/PyMultiNest/issues/175)

**Comment by JohannesBuchner** [comment]
OK. You really have to completely empty build/ (including hidden dot files) so that cmake picks up a different compiler. I think you can also tell it which compiler to use via [command line options](https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake).
