### ISSUE TITLE
Main thread is not in main loop

### ISSUE THREAD

**Issue by alri1472** [JohannesBuchner/PyMultiNest#43]
Hello, there!

I am attempting to figure out how to use MultiNest and PyMultiNest. I believe I have it all installed correctly and I was trying to run pymultinest_demo.py. It successfully gets to the analysis portion of the code however, it is giving me the following error: 

Traceback (most recent call last):
  File "/arlstorage/home/student/alri1472/PyMultiNest/pymultinest_demo.py", line 69, in <module>
    plt.figure(figsize=(5*n_params, 5*n_params))
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/adm/config/python/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 96, in new_figure_manager_given_figure
    icon_img = Tk.PhotoImage(file=icon_fname)
  File "/usr/local/python/lib/python2.7/lib-tk/Tkinter.py", line 3244, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/local/python/lib/python2.7/lib-tk/Tkinter.py", line 3200, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
RuntimeError: main thread is not in main loop

I have only been programming for six months and I have never come across this error before. I was wondering if you could explain this to me and suggest a solution?

Thank you for your time!

**Comment by JohannesBuchner** [comment]
Hi, hope you were able to solve this problem in the meantime. I suspect you tried to call a GUI function to draw something from a thread that was different than the one that created the GUI.

**Comment by alri1472** [comment]
Hello!

Yes, I did solve this problem. If I recall, it had to do with how I was
calling PyMultiNest.

Thanks!
Allyssa
